# To start all docker containers run: `docker-compose up`
#
version: '3'
services:
  app:
    build: .
    command: bash -c "bundle && yarn install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - gem_cache:/gems:delegated
    tty: true
    stdin_open: true
volumes:
  gem_cache: {}
